### ISSUE TITLE
Train with my own data

### ISSUE THREAD

**Issue by Zhu1004** [Audio-WestlakeU/ATST-SED#16]
Hi, @SaoYear .Thank you for your great work.I am a beginner in the field of SED.Now i want to finetune with own data.The problem is that I only have audio files and annotations.I want to ask that how could i change the data folder path in the yaml or how could i modify the code?
Thank you so much

**Comment by chumingqian** [comment]
Hello, brother:  
I am also a beginner in SED, but I think the question you raised would be more appropriate to ask ChatGPT. This is not only a sign of respect for the open-source contributors but also a sign of respect for yourself.

**Comment by SaoYear** [comment]
Hi guys, sorry for being late to response this issue.

@Zhu1004 For your question, I would recommend you to refer to the [DESED baseline repo](https://github.com/DCASE-REPO/DESED_task). Instead of transforming your annotation in `.yaml`, you should re-organized them in to `.csv` files. 

The `.yaml` files are only used for the model training configuration, which follows the rule of [pytorch-lightning](https://lightning.ai/docs/pytorch/stable/). 

The implementations of ATST-SED are indeed somehow complicated for the new-comers. That's because it follows the DESED baseline implementation details, which makes it more friendly to the DCASE challenge participants.

@chumingqian It's okay for me to give suggestions for the new-comers. But thank you for your enthusiasm anyway! 

There are new-comers to the field of SED each year. I am planning to organize a WeChat group for the new-comers so that I do not need to answer the problems repeatly. 
![be59e8d0a8d40a80fe8a80184b3e381](https://github.com/user-attachments/assets/ac81c35e-5572-434f-85d4-8a64e019ece3)

**Comment by SaoYear** [comment]
In case that the QR code could be expired, if any other developer has problems on the SED implementation, please leave a message in this issue.

**Comment by k-li18** [comment]
Thank you very much for your kindness. I am also a newcomer in this field and may I ask how to join the WeChat group you created? Could you please add my WeChat（18519113153）and introduce me to the Wechat group if possible?

**Comment by liu33333** [comment]
> In case that the QR code could be expired, if any other developer has problems on the SED implementation, please leave a message in this issue.如果 QR 码可能过期，如果其他开发人员在 SED 实施方面有问题，请在本期留言。

二维码过期了佬，能更新一下嘛 : )

**Comment by SaoYear** [comment]
可以直接加我wechat 发自我的 iPhone在 2025年4月9日，20:05，ThreeLiu ***@***.***> 写道：﻿
  
In case that the QR code could be expired, if any other developer has problems on the SED implementation, please leave a message in this issue.如果 QR 码可能过期，如果其他开发人员在 SED 实施方面有问题，请在本期留言。

二维码过期了佬，能更新一下嘛 : )—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>



liu33333 left a comment (Audio-WestlakeU/ATST-SED#16)

In case that the QR code could be expired, if any other developer has problems on the SED implementation, please leave a message in this issue.如果 QR 码可能过期，如果其他开发人员在 SED 实施方面有问题，请在本期留言。

二维码过期了佬，能更新一下嘛 : )

**Comment by chief-self** [comment]
你好 还有其他联系方式吗 看不到你的wechat，我想获取一下44k的数据集
