### ISSUE TITLE
Request for dataset！

### ISSUE THREAD

**Issue by Harper812** [Audio-WestlakeU/ATST-SED#5]
Nian Shao, congratulations on your paper being accepted by ICASSP 2024! 
Could you share the external dataset (7384) and annotation file? I would appreciate it if you can help me!

**Comment by SaoYear** [comment]
Hi Harper, 

Thanks for the congradulation ; )

As for your request, I am sorry that I cannot provide you all the .wav files. But what I can do is to provide the full annotation file we used in the ATST-SED work. 

The strongly-labelled AudioSet is very large, and whether uploading or downloading the dataset is time-consuming. On the other hand, Im not sure if we had the correct license to share them, since most files are downloaded from the Youtube and protected by some policies.  You could follow the instructions [here](https://github.com/jim-schwoebel/download_audioset) to download the dataset (might take one month to download the entire unbalanced dataset, but if you specify the filenames, I think it would only take days). PS: I would attempt to upload the files and let you know if I can do so. 

In the annotation file, I annotated each file with: [train/eval] (from AudioSet) + filename. And the event annotation format kept the same as in the DESED dataset.

Enclosed with the annotation file.

[desed_in_audioset_strong.zip](https://github.com/Audio-WestlakeU/ATST-SED/files/13786359/desed_in_audioset_strong.zip)

**Comment by SaoYear** [comment]
@Harper812 Try (this)[https://saoyear.github.io/post/downloading-real-waveforms-for-desed/]

**Comment by Harper812** [comment]
Nian Shao:
Congratulations again!
I’m deeply grateful to you for organizing and sharing the datasets, which will greatly assist me in academic research.
I hope your research achieves fruitful results in the future!

**Comment by SaoYear** [comment]
No problem! Glad to help : )
