### ISSUE TITLE
How to fune-tune the pre-trained model on my custom dataset

### ISSUE THREAD

**Issue by jmren168** [Audio-WestlakeU/ATST-SED#7]
Thanks for the awesome work!

Is it possible to fine-tune the pre-trained model on my custom dataset? Thanks.

**Comment by SaoYear** [comment]
Hi, thanks for your interest.

Of course you can apply fine-tuning by your own dataset. Since the released codes of this work follows the DCASE task 4 baseline, you need to:
1. Re-organize your dataset to the DCASE task 4 (DESED) dataset structure, which includes: your audio waveforms + the meta file (.tsv file) following the meta file format of the DESED dataset.
2. Replace the waveform path and meta file path in the config files. 
3. Following the 2-stage fine-tuning process in this work. 

Hope it helps : )
